name: "Leap Get Environment Variables"
author: RapidCircle
description: "Get Environment Variables"
outputs:
  EnvironmentConfig:
    description: "JSON Object of Environment Variables"
    value: ${{ steps.fetch-environment-variables.outputs.EnvironmentConfig }}
runs:
  using: "composite"
  steps:
    - name: Get Environment Variables
      id: fetch-environment-variables
      shell: pwsh
      # env:
      #   HostURL: ${{ env.HostURL }}
      #   TenantId: ${{ env.TenantId }}
      #   ClientId: ${{ env.ClientId }}
      #   ClientSecret: ${{ env.ClientSecret }}
      #   ServiceIdentifier: ${{ env.ServiceIdentifier }}
      run: ${{ github.action_path }}/script/Get-EnvironmentConfigs.ps1
